car/urls.py
from django.contrib import admin
from django.urls import path
from car_web.views import index, car_index, car_list, car_price, car_view,\
    login, register, logout, change_pwd, car_view2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('index/', car_index),
    path('list/', car_list),
    path('price/', car_price),
    path('view/', car_view),
    path('view2/', car_view2),
    path('login/', login),
    path('register/', register),
    path('logout/', logout),
    path('home/<str:username>/change_pwd/', change_pwd),
]

car_web/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Car(models.Model):
    """车辆信息表"""
    brand_choices = (
        ("audi", "奥迪"),
        ("bmw", "宝马"),
        ("ford", "福特"),
        ("hyundi", "现代"),
        ("merc", "水星"),
        ("skoda", "斯柯达"),
        ("toyota", "丰田"),
        ("vauxhall", "沃克斯豪尔"),
        ("vw", "大众"),
    )
    brand = models.CharField(max_length=32, verbose_name="品牌", choices=brand_choices)
    car_model = models.CharField(max_length=32, verbose_name="模型")
    year = models.CharField(max_length=5, verbose_name="年份")
    price = models.IntegerField(verbose_name="价格")
    transmission = models.CharField(max_length=32, verbose_name="变速器")
    mileage = models.IntegerField(verbose_name="里程")
    fuel_type = models.CharField(max_length=32, verbose_name="汽油种类")
    tax = models.CharField(verbose_name="税额", max_length=32)
    mpg = models.CharField(verbose_name="英里数/每加仑油", max_length=32)
    engine_size = models.CharField(verbose_name="发送机大小", max_length=32)

    def __str__(self):
        for brand_tuple in self.brand_choices:
            if brand_tuple[0] == self.brand:
                return brand_tuple[1] + "|" + self.car_model + "|" + str(self.price)
        return self.brand + "|" + self.car_model + "|" + str(self.price)


class UserInfo(AbstractUser):
    """用户信息"""
    def __str__(self):
        return self.username

car_web/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe
from django.contrib import auth
from car_web.models import Car, UserInfo
from car_web.utils.SwitchUtil import SwitchUtil


def index(request):
    """默认跳转首页"""
    return redirect("/index/")


def car_index(request):
    """首页"""
    return render(request, "car_index.html")


def car_list(request):
    """数据查询页面"""
    su = SwitchUtil()
    # 获取筛选数据
    search_dict = {}
    get_brand = request.GET.get("brand")
    if get_brand:
        search_dict["brand"] = su.big_to_small(get_brand)
    else:
        get_brand = ""
    fuel_type = request.GET.get("fuel_type")
    if fuel_type:
        search_dict["fuel_type"] = fuel_type
    else:
        fuel_type = ""
    min_price = request.GET.get("min_price")
    if min_price:
        search_dict["price__gte"] = int(min_price)
    else:
        min_price = ""
    max_price = request.GET.get("max_price")
    if max_price:
        search_dict["price__lte"] = int(max_price)
    else:
        max_price = ""

    # 分页渲染MySQL数据
    from car_web.utils.pagination import Pagination
    queryset = Car.objects.filter(**search_dict)
    page = Pagination(request, "page", queryset, page_size=15,
                      form_switch=True, last_switch=True, first_switch=True, a_prev=True, a_next=True)

    # 获取所有的品牌
    from car_web.utils.load import Load
    load = Load("D:/Python_Project/car/car_web/static/file/archive/")
    brand_list = [su.big_to_small(i.split(".")[0]) for i in load.brand_list]
    brand_option_html_string = f"<option></option><option selected>{get_brand}</option>"

    for brand in brand_list:
        if brand == get_brand:
            continue
        else:
            brand_option_html_string += f"<option>{brand}</option>"

    # 传给前端的数据
    response = {
        "car_data": page.page_queryset,
        "page_html_string": page.html(),
        "brand_option_html_string": mark_safe(brand_option_html_string),
        "type_val": fuel_type,
        "min_price_val": min_price,
        "max_price_val": max_price,
    }
    return render(request, "car_list.html", response)


def car_view(request):
    """数据大屏页面"""
    # 加载大数据分析出的json文件
    from car_web.utils.LoadData import LoadJsonToView
    # brand柱状图数据载入
    ljv1 = LoadJsonToView("D:/Python_Project/car/car_web/static/file/output/brandGroupDataNum", "brand")

    # 最大最小价格
    min_price = Car.objects.all().order_by("price").first()
    max_price = Car.objects.all().order_by("-price").first()
    # 传给前端的数据
    su = SwitchUtil()
    response = {
        # icon数据
        "brand_num": len(su.big_list),
        "car_info_num": Car.objects.all().count,
        "min_price": min_price,
        "max_price": max_price,
        # 柱状图数据
        "brand_list": mark_safe(str([su.big_to_small(i) for i in ljv1.make_bar_data()[0]])),
        "brand_list_num": mark_safe(str([i for i in ljv1.make_bar_data()[1]])),

    }
    return render(request, "car_view.html", response)


def car_view2(request):
    """数据大屏2"""
    # 加载大数据分析出的json文件
    from car_web.utils.LoadData import LoadJsonToView
    # fuelType饼图数据载入
    ljv2 = LoadJsonToView("D:/Python_Project/car/car_web/static/file/output/fuelTypeGroupDataNum", "fuel_type")
    # icon
    fuel_type = Car.objects.values("fuel_type").distinct().count()
    year_type = Car.objects.values("year").distinct().count()
    # mileage
    mileages = Car.objects.values("mileage")
    mileage_type = {
        "<5000": 0,
        "5000-10000": 0,
        "10000-20000": 0,
        ">20000": 0,
    }
    for mileage in mileages:
        if mileage["mileage"] < 5000:
            mileage_type["<5000"] += 1
        elif mileage["mileage"] < 10000:
            mileage_type["5000-10000"] += 1
        elif mileage["mileage"] < 20000:
            mileage_type["10000-20000"] += 1
        else:
            mileage_type[">20000"] += 1
    mileage_list = []
    for k, v in mileage_type.items():
        mileage_list.append(f'{"{"}"name": "{k}", "value": {v}{"}"}')

    # year
    years = Car.objects.values("year")
    year_type_dict = {
        "<2000": 0,
        "2000-2010": 0,
        "2010-2015": 0,
        "2015-2020": 0,
        ">2020": 0,
    }
    for year in years:
        print(type(year["year"]))
        if year["year"] < "2000":
            year_type_dict["<2000"] += 1
        elif year["year"] < "2010":
            year_type_dict["2000-2010"] += 1
        elif year["year"] < "2015":
            year_type_dict["2010-2015"] += 1
        elif year["year"] < "2020":
            year_type_dict["2015-2020"] += 1
        else:
            year_type_dict[">2020"] += 1
    year_list = []
    for k, v in year_type_dict.items():
        year_list.append(f'{"{"}"name": "{k}", "value": {v}{"}"}')
    response = {
        "fuel_type": fuel_type,
        "year_type": year_type,
        # 饼图数据
        "fuel_type_str": mark_safe(ljv2.make_pie_data()),
        "mileage_list": mark_safe(",".join(mileage_list)),
        "year_list": mark_safe(",".join(year_list)),
    }
    return render(request, "car_view2.html", response)


def car_price(request):
    """价格预测页面"""
    from car_web.utils.PricePredict import PricePredict, FieldSwitch
    # 传给前端的数据
    response = {}
    fs = FieldSwitch(Car)
    su = SwitchUtil()
    # 获取前端数据
    if request.method == "POST":
        brand = fs.brand_sw(su.big_to_small(request.POST.get("brand")))
        car_model = fs.car_model_sw(request.POST.get("car_model"))
        fuel_type = fs.fuel_type_sw(request.POST.get("fuel_type"))
        transmission = fs.transmission_sw(request.POST.get("transmission"))
        year = int(request.POST.get("year"))
        mileage = int(request.POST.get("mileage"))

        # 预测
        temp = fs.numpy_load()
        pp = PricePredict(temp["x"], temp["y"])
        # 品牌、模型、年份、里程数、汽油种类、变速器
        predict = pp.predict_res([brand, car_model, year, mileage, fuel_type, transmission])[0]
        response["predict_price"] = int(predict/10000)
    else:
        response["predict_price"] = 0

    # brand select 生成
    brand_html_string = ""
    for brand in fs.brands:
        if brand == su.big_to_small(request.POST.get("brand")):
            brand_html_string += f"<option selected>{su.big_to_small(brand)}</option>\n"
        else:
            brand_html_string += f"<option>{su.big_to_small(brand)}</option>\n"
    response["brand_option_html_string"] = mark_safe(brand_html_string)

    # car_model select 生成
    car_model_html_string = ""
    for car_model in fs.car_models:
        if car_model == request.POST.get("car_model"):
            car_model_html_string += f"<option selected>{car_model}</option>\n"
        else:
            car_model_html_string += f"<option>{car_model}</option>\n"
    response["car_model_option_html_string"] = mark_safe(car_model_html_string)

    # fuel_type select 生成
    fuel_type_html_string = ""
    for fuel_type in fs.fuel_types:
        if fuel_type == request.POST.get("fuel_type"):
            fuel_type_html_string += f"<option selected>{fuel_type}</option>\n"
        else:
            fuel_type_html_string += f"<option>{fuel_type}</option>\n"
    response["fuel_type_option_html_string"] = mark_safe(fuel_type_html_string)

    # transmission select 生成
    transmission_html_string = ""
    for transmission in fs.transmissions:
        if transmission == request.POST.get("transmission"):
            transmission_html_string += f"<option selected>{transmission}</option>\n"
        else:
            transmission_html_string += f"<option>{transmission}</option>\n"
    response["transmission_option_html_string"] = mark_safe(transmission_html_string)

    # 保留传递值
    response["year"] = request.POST.get("year", "")
    response["mileage"] = request.POST.get("mileage", "")

    return render(request, "car_price.html", response)


def login(request):
    """登录界面"""
    if request.method == "POST":
        response = {
            "user": None,
            "msg": None,
        }
        user = request.POST.get("user")
        pwd = request.POST.get("pwd")
        user = auth.authenticate(username=user, password=pwd)
        if user:
            auth.login(request, user)
            response["user"] = user.username
        else:
            response["msg"] = "用户名或密码错误！"
        return JsonResponse(response)

    return render(request, 'login.html')


def register(request):
    """注册界面"""
    from car_web.utils.my_forms import UserForm
    if request.is_ajax():
        form = UserForm(request.POST)
        response = {"user": None, "msg": None}
        if form.is_valid():
            response["user"] = form.cleaned_data.get("user")
            user = form.cleaned_data.get("user")
            pwd = form.cleaned_data.get("pwd")
            UserInfo.objects.create_user(username=user, password=pwd)
        else:
            response["msg"] = form.errors
        return JsonResponse(response)
    form = UserForm()
    return render(request, "register.html", {"form": form})


def logout(request):
    """注销操作"""
    auth.logout(request)
    return redirect("/login/")


def change_pwd(request, username):
    response = {
        "username": username,
        "error": "",
    }
    if request.method == "POST":
        pwd = request.POST.get("pwd")
        re_pwd = request.POST.get("re_pwd")
        user = auth.authenticate(username=username, password=pwd)
        if user:
            u = UserInfo.objects.get(username__exact=username)
            u.set_password(re_pwd)
            u.save()
            auth.logout(request)
            return redirect("/login/")
        else:
            response["error"] = "密码错误！"
            return render(request, "change_pwd.html", response)
    return render(request, "change_pwd.html", response)

car_web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入css -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
<!-- 导航栏 -->
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">车辆价格预测平台</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% block nav_list%}{% endblock %}
            </ul>
            <!-- 右侧部分 -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="#">当前用户：{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">用户管理 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/home/{{ request.user.username }}/change_pwd/">修改密码</a></li>
                            <li><a href="/logout/">切换账号</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/logout/">退出登录</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- 网页主体 -->
{% block content %}{% endblock %}

<!-- 引入js -->
<script rel="script" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script rel="script" src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

car_web/templates/car_index.html
{% extends 'base.html' %}
{% load static %}

<!-- 网页标题 -->
{% block title %}
    【车辆价格预测平台】主页
{% endblock %}

<!-- 导航栏列表 -->
{% block nav_list %}
    <li class="active"><a href="/index/">主页</a></li>
    <li><a href="/view/">数据大屏</a></li>
    <li><a href="/list/">数据查询</a></li>
    <li><a href="/price/">价格预测</a></li>
{% endblock %}

<!-- css样式 -->
{% block css %}
    <style>
        .side_img {
            width: 92%;
            margin-top: 10px;
        }

        .content {
            width: 96%;
        }

        .content h3 {
            margin-left: 10px;
        }

        .content p {
            margin-left: 10px;
        }

        .content div {
            margin-left: 10px;
            margin-bottom: 15px;
            height: 120px;
        }
    </style>
{% endblock %}

<!-- 网页主体 -->
{% block content %}
    <!-- 三栏显示 -->
    <div class="container">
        <div class="col-sm-6 col-md-4">
            <div class="modal-content thumbnail">
                <img class="side_img img-rounded " src="{% static 'imgs/index_1.png' %}" alt="首页图1.png">
                <div class="content caption">
                    <h3 class="h3 text-primary">海量信息</h3>
                    <hr class="divider">
                    <div class="text-left text-muted">
                        平台收集了奥迪、宝马等<mark>13个品牌</mark>，<mark>每种</mark>品牌价格数据<mark>超1w条</mark>。<br>
                        海量信息供用户查询，力求全面。
                    </div>
                    <p class="text-right">
                        <a href="#" class="btn btn-primary" role="button">了解更多</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="modal-content thumbnail">
                <img class="side_img img-rounded " src="{% static 'imgs/index_2.png' %}" alt="首页图2.png">
                <div class="content caption">
                    <h3 class="h3 text-primary">价格筛选</h3>
                    <hr class="divider">
                    <div class="text-left text-muted">
                        平台提供多种筛选器，支持组合筛选，
                        包括<mark>价格区间</mark>、<mark>品牌</mark>、<mark>汽油种类</mark>等筛选标准。<br>
                        用户可以在海量数据中，迅速获取自己想要的。
                    </div>
                    <p class="text-right">
                        <a href="#" class="btn btn-primary" role="button">了解更多</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="modal-content thumbnail">
                <img class="side_img img-rounded " src="{% static 'imgs/index_3.png' %}" alt="首页图3.png">
                <div class="content caption">
                    <h3 class="h3 text-primary">价格预测</h3>
                    <hr class="divider">
                    <div class="text-left text-muted">
                        基于平台海量数据，利用<mark>智能算法</mark>，结合行情，给用户提供适当的价位参考。<br>
                        输入几个数据，即可获取价格预测。
                    </div>
                    <p class="text-right">
                        <a href="#" class="btn btn-primary" role="button">了解更多</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <hr class="container modal-content divider">
    <!-- 页脚 -->
    <div class="container-fluid panel-footer">
        <table class="table">
        </table>
        <footer class="container">
            <p>&copy; 2022 | LH | 界面还有待完善，欢迎给出指导意见 | 车辆价格预测平台</p>
        </footer>
    </div>
{% endblock %}

car_web/templates/car_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    【车辆价格预测平台】数据查询
{% endblock %}

{% block nav_list %}
    <li><a href="/index/">主页</a></li>
    <li><a href="/view/">数据大屏</a></li>
    <li class="active"><a href="/list/">数据查询</a></li>
    <li><a href="/price/">价格预测</a></li>
{% endblock %}
{% block css %}
    <style>
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <form class="form-inline">
                {% csrf_token %}
                <div class="form-group">
                    <label class="text" for="brand">品牌：</label>
                    <select class="form-control" id="brand" style="width: 120px" name="brand">
                        {{ brand_option_html_string }}
                    </select>
                </div>
                <div class="form-group" style="padding-left: 20px">
                    <label class="text" for="fuel_type">汽油种类：</label>
                    <input type="text" class="form-control" id="fuel_type" style="width: 200px"
                           placeholder="汽油种类" value="{{ type_val }}" name="fuel_type">
                </div>
                <div class="form-group" style="padding-left: 20px">
                    <label class="text" for="price">价格区间：</label>
                    <label class="sr-only" for="min_price">最低价格</label>
                    <input type="text" class="form-control" id="min_price" style="width: 120px"
                           placeholder="最低价格" value="{{ min_price_val }}" name="min_price">
                    <span class="text">-</span>
                    <label class="sr-only" for="max_price">最高价格</label>
                    <input type="text" class="form-control" id="max_price" style="width: 120px"
                           placeholder="最高价格" value="{{ max_price_val }}" name="max_price">
                </div>
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </form>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
                数据列表
            </div>
        </div>
        <table class="table table-striped table-hover" style="margin-top: -20px">
            <thead>
            <tr class="info">
                <th>数据ID</th>
                <th>品牌</th>
                <th>模型</th>
                <th>年份</th>
                <th>价格</th>
                <th>变速器</th>
                <th>里程</th>
                <th>汽油种类</th>
                <th>税额</th>
                <th>英里数/每加仑油</th>
                <th>发动机大小</th>
            </tr>
            </thead>
            <tbody>
            {% for car in car_data %}
                <tr>
                    <td>{{ car.id }}</td>
                    <td>{{ car.get_brand_display }}</td>
                    <td>{{ car.car_model }}</td>
                    <td>{{ car.year }}</td>
                    <td>{{ car.price }}</td>
                    <td>{{ car.transmission }}</td>
                    <td>{{ car.mileage }}</td>
                    <td>{{ car.fuel_type }}</td>
                    <td>{{ car.tax }}</td>
                    <td>{{ car.mpg }}</td>
                    <td>{{ car.engine_size }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <ul class="pagination" style="margin-top: -10px">
            {{ page_html_string }}
        </ul>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

car_web/templates/car_price.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    【车辆价格预测平台】价格预测
{% endblock %}

{% block nav_list %}
    <li><a href="/index/">主页</a></li>
    <li><a href="/view/">数据大屏</a></li>
    <li><a href="/list/">数据查询</a></li>
    <li class="active"><a href="/price/">价格预测</a></li>
{% endblock %}
{% block css %}
    <style>

    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
                    价格预测
                </h3>
            </div>
            <div class="panel-body">
                <form class="form" method="post">
                    {% csrf_token %}
                    <div class="form-group"><div class="col-sm-6">
                        <label class="text" for="brand">品牌：</label>
                        <select class="form-control" id="brand" style="margin-bottom: 20px" name="brand">
                            {{ brand_option_html_string }}
                        </select>
                    </div></div>
                    <div class="form-group"><div class="col-sm-6">
                        <label class="text" for="car_model">车辆模型：</label>
                        <select class="form-control" id="car_model" style="margin-bottom: 20px" name="car_model">
                            {{ car_model_option_html_string }}
                        </select>
                    </div></div>
                    <div class="form-group"><div class="col-sm-6">
                        <label class="text" for="fuel_type">汽油种类：</label>
                        <select class="form-control" id="fuel_type" style="margin-bottom: 10px" name="fuel_type">
                            {{ fuel_type_option_html_string }}
                        </select>
                    </div></div>
                    <div class="form-group"><div class="col-sm-6">
                        <label class="text" for="transmission">变速器：</label>
                        <select class="form-control" id="transmission" style="margin-bottom: 10px" name="transmission">
                            {{ transmission_option_html_string }}
                        </select>
                    </div></div>
                    <div class="form-group">
                        <div class="col-sm-6" style="padding-top: 10px">
                            <label for="year">年份</label>
                            <input type="text" class="form-control" name="year" id="year" placeholder="年份" value="{{ year }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6" style="padding-top: 10px">
                            <label for="mileage">里程数</label>
                            <input type="text" class="form-control" name="mileage" id="mileage" placeholder="行驶里程数" value="{{ mileage }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-8" style="padding-top: 20px">
                            <button type="reset" class="btn btn-default">重 置</button>
                            <button type="submit" class="btn btn-success">预测价格</button>
                        </div>

                        <!-- 预测结果显示 -->
                        <div class="col-sm-4" style="padding-top: 20px">
                            <p class="text">
                                预测价格结果为：
                                <span class="h2 text-danger">{{ predict_price }}</span>&emsp;<small class="h3 text-info">±1000</small>
                            </p>

                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

car_web/templates/car_view.html
{% extends 'view_base.html' %}
{% load static %}

{% block breadcrumb-tip %}
数据概览
{% endblock %}

{% block left-list %}
    <li role="presentation" class="active"><a href="/view/">数据概览</a></li>
    <li role="presentation"><a href="/view2/">分布概览</a></li>
{% endblock %}

{% block right-main %}
    <div class="col-lg-3" style="height: 120px;">
        <button class="list-group-item btn-default" style="width: 100%;">
            <h4 class="text-center text-info">品牌数</h4>
            <p class="text-center">{{ brand_num }}</p>
        </button>
    </div>
    <div class="col-lg-3" style="height: 120px;">
        <button class="list-group-item btn-default" style="width: 100%;">
            <h4 class="text-center text-info">总数据条数</h4>
            <p class="text-center">{{ car_info_num }}</p>
        </button>
    </div>
    <div class="col-lg-3" style="height: 120px;">
        <button class="list-group-item btn-default" style="width: 100%;">
            <h4 class="text-center text-info">最低价格</h4>
            <p class="text-center">{{ min_price }}</p>
        </button>
    </div>
    <div class="col-lg-3" style="height: 120px;">
        <button class="list-group-item btn-default" style="width: 100%;">
            <h4 class="text-center text-info">最高价格</h4>
            <p class="text-center">{{ max_price }}</p>
        </button>
    </div>
    <div class="col-lg-12" id="brand_bar" style="height: 300px"></div>
{% endblock %}

{% block js %}
    <script rel="script" src="{% static 'js/echarts.js' %}"></script>
    <script rel="script" src="{% static 'js/shine.js' %}"></script>
    <script rel="script" src="{% static 'js/macarons.js' %}"></script>
    <!-- 柱状图 bar -->
    <script>
        let brand_bar = echarts.init(document.querySelector("#brand_bar"));

        let option_bar = {
            color: ["#5ab1ef", "#2ec7c9", "#b6a2de", "#ffb980", "#d87a80", "#8d98b3"],
            title: {
                text: "各品牌信息数",
                top: "2%",
                left: "2%",
            },
            backgroundColor: "rgb(245, 245, 245)",
            tooltip: {
                trigger: 'axis',
                axisPointer: {            // 坐标轴指示器，坐标轴触发有效
                    type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                }
            },
            toolbox: {
                right: "2%",
                top: "2%",
                feature: {
                    dataView: {show: true, readOnly: false},
                    magicType: {show: true, type: ['line']},
                    restore: {show: true},
                    saveAsImage: {show: true}
                }
            },
            legend: {
                left: "center",
                top: "2%",
                data: ['数量']
            },
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            xAxis: [
                {
                    type: 'category',
                    data: {{ brand_list }},
                }
            ],
            yAxis: [
                {
                    type: 'value'
                }
            ],
            series: [
                {
                    name: '数量',
                    type: 'bar',
                    stack: '总数量',
                    emphasis: {
                        focus: 'series'
                    },
                    data: {{ brand_list_num }},
                    label: {
                        show: true,
                        position: 'inside',
                        color: "#fff"
                    },
                },
            ]
        };

        brand_bar.setOption(option_bar);
        window.addEventListener("resize", function () {
            brand_bar.resize();
        });
    </script>
{% endblock %}

car_web/templates/change_pwd.html
{% extends 'base.html' %}

{% block title %}
修改密码
{% endblock %}

{% block nav_list %}

{% endblock %}

{% block css %}
    <style>
        #error {
            color: red;
        }
    </style>
{% endblock %}

{% block content %}
<div class="container">
<form id="form" action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="user">用户名：</label>
        <input id="user" name="user" type="text" class="form-control" value="{{ request.user.username }}" disabled/>
    </div>

    <div class="form-group">
        <label for="pwd">原密码：</label>
        <input id="pwd" name="pwd" type="password" class="form-control"/><span class="error pull-right"></span>
    </div>
    <div class="form-group">
        <label for="re_pwd">新密码：</label>
        <input id="re_pwd" name="re_pwd" type="password" class="form-control"/><span class="error pull-right"></span>
    </div>

    <div class="form-group">
        <input type="submit" class="change_btn btn btn-primary"/>&nbsp;
        <input type="reset" class="btn btn-default"/>&emsp;<span id="error">{{ error }}</span>
    </div>
</form>
</div>
{% endblock %}

{% block js %}

{% endblock %}